version: 0.2

phases:
  install:
    runtime-versions:
      python: latest
    commands:
      - echo "Installing Terraform..."
      - curl -O https://releases.hashicorp.com/terraform/1.5.6/terraform_1.5.6_linux_amd64.zip
      - unzip terraform_1.5.6_linux_amd64.zip
      - mv terraform /usr/local/bin/
      - terraform --version

  pre_build:
    commands:
      - echo "Initializing Terraform..."
      - terraform init

  build:
    commands:
      - echo "Validating Terraform Configuration..."
      - terraform validate
      - echo "Planning Terraform Changes..."
      - terraform plan

  post_build:
    commands:
      - echo "Applying Terraform Configuration..."
      - terraform apply -auto-approve
      - echo "Terraform Apply Completed"

artifacts:
  files:
    - '**/*'
